### ADMIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "1234",
  "password": "123"
}

### MODERATOR auht
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "alish",
  "password": "123"
}


###
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "alish",
  "password": "123"
}

###
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "admin",
  "surname": "adminjon",
  "email": "1234",
  "password": "123"
}

###SUER_MODERATOR

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "234",
  "password": "123"
}

###
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "user1",
  "surname": "user1",
  "email": "1212",
  "password": "434343",
  "phone": "123454321"
}

###

POST http://localhost:8080/auth/verification
Content-Type: application/json

{
  "phone": "123454321",
  "code": "58519"
}
