### ADMIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "1234",
  "password": "123"
}

### MODERATOR auht
POST http://localhost:8082/auth/login
Content-Type: application/json

{
  "email": "alish",
  "password": "123"
}


###
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "alish",
  "password": "123"
}

### security
POST http://localhost:8082/auth/registration
Content-Type: application/json

{
  "name": "admin",
  "surname": "adminjon",
  "email": "hasan6453552@gmail1.com",
  "phone": "1234121221",
  "password": "123"
}

###Security
POST http://localhost:8082/auth/login
Content-Type: application/json

{
  "email": "hasan6453552@gmail1.com",
  "password": "123"
}
###SUER_MODERATOR

POST http://localhost:8080/auth/login
Content-Type: application/json

{
"email": "234",
"password": "123"
}


###
POST http://localhost:8082/auth/registration
Content-Type: application/json

{
  "name": "user1",
  "surname": "user1",
  "email": "alis12h.com",
  "password": "434",
  "phone": "212112"
}

###

POST http://localhost:8080/auth/verification
Content-Type: application/json

{
  "phone": "123454321",
  "code": "58519"
}

###
GET http://localhost:8080/auth/email/verification/29

###
POST http://localhost:8080/auth/resend/email/29