POST http://localhost:8082/category/adm
Content-Type: application/json
Authorization: Basic 1234 123

{
  "nameUz": "categoryUz2",
  "nameRu": "categoryRu2",
  "nameEn": "categoryEn2"
}

###
PUT http://localhost:8080/category/1
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5MzA4OTYsImV4cCI6MTY1NDkzNDQ5NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hhtD4MGhdAyvIRlEBcQL8r3oQ6k_HVvMU1F_UWpyC2I

{
  "nameUz": "categoryUzUpdate",
  "nameRu": "categoryRuUpdate",
  "nameEn": "categoryEnUpdate"
}

###
GET http://localhost:8080/category/list
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5MzA4OTYsImV4cCI6MTY1NDkzNDQ5NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hhtD4MGhdAyvIRlEBcQL8r3oQ6k_HVvMU1F_UWpyC2I


###
DELETE http://localhost:8080/category/1
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5MzA4OTYsImV4cCI6MTY1NDkzNDQ5NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hhtD4MGhdAyvIRlEBcQL8r3oQ6k_HVvMU1F_UWpyC2I
