POST http://localhost:8082/comment
Content-Type: application/json
Authorization: Basic 111 123

{
  "content": "content1",
  "articleId": "4028b6cd8152e3a7018152e3ca520000",
  "commentId": 3

}

###
PUT http://localhost:8080/comment/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUwMjc2NTcsImV4cCI6MTY1NTAzMTI1NywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo0LCJyb2xlIjoiVVNFUiJ9._S9hayum6X2U69iWSSmAwkV_VEQD9IWDwJdVm4Ve5oE

{

  "content": "update3",
  "articleId": "4028b6cd8152e3a7018152e3ca520000"

}