POST http://localhost:8080/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3NzgwNjEsImV4cCI6MTY1NDc4MTY2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.BH0f5GeFqHGe-UvUa4UrQuOWAg_4waeZByyaqFKpdlo

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "email1",
  "password": "123"
}


###

PUT http://localhost:8080/profile/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3NzgwNjEsImV4cCI6MTY1NDc4MTY2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.BH0f5GeFqHGe-UvUa4UrQuOWAg_4waeZByyaqFKpdlo

{
  "name": "Toshmat",
  "surname": "Toshmatov"
}

###
PUT http://localhost:8080/profile/detail/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3NzgwNjEsImV4cCI6MTY1NDc4MTY2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.BH0f5GeFqHGe-UvUa4UrQuOWAg_4waeZByyaqFKpdlo

{
  "name": "ToshmatJon",
  "surname": "Toshov"
}


###

POST http://localhost:8080/profile/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYwNTEzOTQsImV4cCI6MTY1NjEzNzc5NCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiQURNSU4ifQ.OmAUHWPl5mwOqdI_x9XSpn6U0SIPDywrmF-aCfxCaGk

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pictory.jfif"

< C:\Users\user\Desktop\pictory.jfif
